Check Order Manager task
ttemuchin/TL_practice pull request #1
Opened 2024-07-02 11:07 UTC by ttemuchin

2024-07-08 08:52 UTC, AlexPshkov requested changes

2024-07-08 08:52 UTC, AlexPshkov commented on OrderManager/OrderManager/Program.cs
> +    bool flag = false;
Назвать флаг просто `flag` это конечно можно, но тут бы лучше дать более конкретное название

2024-07-08 08:52 UTC, AlexPshkov commented on OrderManager/OrderManager/Program.cs
> +static void Message( string[] data )
Передавать так параметры для вывода в сообщении довольно странное решение. Если уж все-равно указываешь вручную в строке все это, то лучше уж передал бы все эти четыре параметра на прямую, а не в массиве.

2024-07-08 08:52 UTC, AlexPshkov commented on OrderManager/OrderManager/Program.cs
> +static string ReadProductName()
Все эти функции ReadProductName, ReadQuantity, ReadUserName и т.д можно скоратить до двух функций ReadString и ReadNumber. Логика в каждой из этих функций абсолютно одинаковая

2024-07-08 08:52 UTC, AlexPshkov commented on OrderManager/OrderManager/Program.cs
> +static bool Confirm( string name, int quantity, string product, string address )
Тут ведь наверно не глагол нужен, а что-то типа: `IsConfirmed ` или `ReadConfirmation`

2024-07-29 19:50 UTC, ttemuchin commented on OrderManager/OrderManager/Program.cs
> +static void Message( string[] data )
да, это оочень странно. но это так, на первых парах

2024-07-29 19:56 UTC, ttemuchin commented on OrderManager/OrderManager/Program.cs
> +static string ReadProductName()
dry, understood

2024-08-22 14:11 UTC, merged