Dictionary task
ttemuchin/TL_practice pull request #2
Opened 2024-07-02 14:06 UTC by ttemuchin

2024-07-08 08:57 UTC, AlexPshkov requested changes

2024-07-08 08:57 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +Main();
`public static void Main( string[] args )` И так является точкой входа в программу по умолчанию. В вызове его вот так нет никакой необходимости

2024-07-08 08:57 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +    while ( active )
Слишком большой метод `while`. Разбей его тело на отдельные функции, чтобы при взгляде на этот метод было сразу понятно что вообще тут происходит

2024-07-08 08:57 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +    using ( StreamWriter sw = new StreamWriter( fstream ) )
Можно было просто `using TextWriter writer = new StreamWriter( PathToFile, true );`. Без `FileStream`

2024-07-29 20:31 UTC, ttemuchin commented on Dictionary/Dictionary/Program.cs
> +    while ( active )
done

2024-08-07 20:47 UTC, AlexPshkov requested changes

2024-08-07 20:47 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +    foreach ( var word in dict )
`var` используем только тогда, когда и так понятно какой тип данных у переменной. В данном же случае это не явно и тут бы лучше указать его

2024-08-07 20:47 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +static void ShowDict()
Вместо `ShowDict` предлагаю использовать `PrintAllWords`

2024-08-07 20:47 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +    //using ( FileStream fstream = new FileStream( path, FileMode.Append, FileAccess.Write ) )
Если код не нужен, дак удали его...

2024-08-07 20:47 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +    Console.WriteLine( dict[ word ] );
Если такого слова не будет, то он у тебя упадет с ошибкой. Добавь проверку на наличие

2024-08-07 20:47 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +static Dictionary<string, string> OpenDictionary()
Тут уж скорее `LoadDictionaryFromFile` иди `GetDictionaryFromFile`

2024-08-13 04:00 UTC, ttemuchin commented on Dictionary/Dictionary/Program.cs
> +    //using ( FileStream fstream = new FileStream( path, FileMode.Append, FileAccess.Write ) )
)) и правда

2024-08-20 14:38 UTC, AlexPshkov approved these changes

2024-08-22 14:13 UTC, merged