features/Fighters
ttemuchin/TL_practice pull request #4
Opened 2024-07-27 13:36 UTC by ttemuchin

2024-08-07 21:03 UTC, AlexPshkov requested changes

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters.Test/GameManagerTest.cs
> +            var winner = gameManager.Game( fighterA, fighterB );
Тип не явен. Лучше без `var`

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters.Test/GameManagerTest.cs
> +        public void Play_TwoEqualFighters_SecondFighterDies()
У тебя же метод называется не `Play`, а `Game`

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            var userData = new Dictionary<string, string>();
Сомнительное решение использовать для хранения конфигурации словарик. Можно ведь было сделать отдельный объект для этого и тогда бы можно было сразу создать все объекты с аттрибутами

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/Extensions/IFighterExtensions.cs
> +        /*      public Fighter Configuration( IRace race, IClass user_class, IWeapon weapon )
Если код не нужен - удали

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/GameManager.cs
> +                //Thread.Sleep( 1000 );
Если код не нужен - удали

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/GameManager.cs
> +                    if ( Math.Round( rand.NextDouble(), 2 ) >= 0.88 )
Убери "магические" числа из кода. Можно либо в константы на верх класса, либо просто в отдельные перменные в этом методе, но главное чтоб было понятно что эти числа означают. (Не только здесь, но и ниже то же)

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/GameManager.cs
> +                //Console.ReadKey( true );
Не нужно - удали. Не храни код в комментариях

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/GameManager.cs
> +                if ( round >= 10 )
Такой же код есть на 20 строчке, а значит его уже можно вынести в отдельную функцию. Да и вообще этот метод выглядит очень громоздки и непонятным. Попробуй его сделать "красивее"

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            if ( userData[ "race" ] == "dwarf" ) { race = new Dwarf(); }
Давай лучше использовать оператор `switch` для подобных действий

2024-08-07 21:03 UTC, AlexPshkov commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            var race = new Object();
Это плохая идея. Сделай просто `null`

2024-08-15 07:09 UTC, ttemuchin commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            if ( userData[ "race" ] == "dwarf" ) { race = new Dwarf(); }
даааа!

2024-08-15 07:09 UTC, ttemuchin commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            var race = new Object();
мне нравится это решение. если это тоже костыль, то явно лучше

2024-08-16 11:07 UTC, ttemuchin commented on FightersGame/Fighters/Extensions/Configuration.cs
> +            var userData = new Dictionary<string, string>();
не совсем понял. сейчас данные пользователя идут так: строка - словарь - создание объектов всех параметров - передача - сбор всего в новом файтере. как изменить этот путь?

2024-08-16 11:17 UTC, ttemuchin commented on FightersGame/Fighters/GameManager.cs
> +                    if ( Math.Round( rand.NextDouble(), 2 ) >= 0.88 )
TakeDamage() тоже очистил от этого

2024-08-20 14:40 UTC, AlexPshkov approved these changes

2024-08-22 14:13 UTC, merged