features/car factory
ttemuchin/TL_practice pull request #5
Opened 2024-07-29 03:50 UTC by ttemuchin

2024-08-07 21:11 UTC, AlexPshkov requested changes

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory.Test/EqualPricesTest.cs
> +        public void EqualPrices()
Название должно быть в формате `ТестируемыйМетод_ТестируемыйКейс_ОжидаемыйРезультат`

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory.Test/EqualPricesTest.cs
> +    public class EqualPricesTest
Ты ведь тестируешь класс `BuildManager`

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory/Extensions/Configuration.cs
> +            var userData = new Dictionary<string, string>();
Для этого лучше создать отдельный объект, а не хранить все это в словаре

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory/Extensions/Configuration.cs
> +            var engine = new Object();
Лучше инициализировать пустым значением `null`, а в качестве типа использовать не `var`, а интерфейс

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory/Extensions/Configuration.cs
> +            if ( userData[ "color" ] == "pink" ) { color = new Pink(); }
Используй оператор `switch`

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory/Models/Car.cs
> +            var speed = _engine.Power * 20 + 40 - _shape.Resistance * 4;
Запихни эти числа в константы/переменные и дай или хотя бы комментарий напиши

2024-08-07 21:11 UTC, AlexPshkov commented on CarFactory/CarFactory/Program.cs
> +                var BM = new BuildManager();
не называй так. Лучше просто `buildManager`

2024-08-19 12:35 UTC, ttemuchin commented on CarFactory/CarFactory/Models/Car.cs
> +            var speed = _engine.Power * 20 + 40 - _shape.Resistance * 4;
Понял. Пусть в этом проекте эти константы будут странно названы, главное - сказать нет магическим числам

2024-08-19 12:47 UTC, ttemuchin commented on CarFactory/CarFactory/Extensions/Configuration.cs
> +            var userData = new Dictionary<string, string>();
сделано. правильно понимаю, что лучше использовать объекты а не структуры данных из-за модификаторов доступа?

2024-08-20 14:41 UTC, AlexPshkov approved these changes

2024-08-22 14:13 UTC, merged